org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.2.20
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1
mod_id=alltheimbaium
mod_name=Alltheimbaium
mod_license=GNU LGPL v3
mod_version=1.0.0
mod_group_id=cn.sd.jrz
# \u53EF\u9009\u8054\u52A8 JEI\uFF1A\u53EA\u7528\u5B83\u7684 api \u5236\u54C1\u505A\u7F16\u8BD1\u671F\u4F9D\u8D56\uFF08\u89C1 build.gradle\uFF09\uFF0C\u8FD0\u884C\u671F\u4E0D\u6253\u5305\u3002
# \u7248\u672C\u53D6**\u8981\u652F\u6301\u7684\u6700\u8001\u7248\u672C**\u2014\u2014JEI \u7684 api \u4F1A\u5411\u524D\u52A0\u65B9\u6CD5\uFF08\u5982 addRecipeArrowWidget \u662F 15.56 \u624D\u6709\u7684\uFF09\uFF0C
# \u6309\u65B0\u7248\u672C\u7F16\u8BD1\u51FA\u6765\u7684 jar \u88C5\u8FDB\u8001\u7248\u672C JEI \u5C31\u4F1A NoSuchMethodError\uFF1B\u6309\u8001\u7248\u672C\u7F16\u8BD1\u5219\u53EF\u901A\u5403 15.20~\u6700\u65B0\u3002
jei_version=15.20.0.112
mod_authors=JRZ
mod_description=Added some machines that disrupt the balance.