org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.41-beta
mod_id=alltheimbaium
mod_name=Alltheimbaium
mod_license=GNU LGPL v3
mod_version=1.0.1
mod_group_id=cn.sd.jrz
mod_authors=JRZ
mod_description=Added some machines that disrupt the balance.
# \u53EF\u9009\u8054\u52A8 JEI\uFF0826.1.2 \u7EBF\uFF09\uFF1A\u53EA\u7528 api \u5236\u54C1\u505A\u7F16\u8BD1\u671F\u4F9D\u8D56\uFF0C\u8FD0\u884C\u671F\u4E0D\u6253\u5305
# \u7F16\u8BD1\u57FA\u7EBF\u53D6\u201C\u8981\u652F\u6301\u7684\u6700\u8001 JEI \u7248\u672C\u201D\uFF0C\u4E0D\u8981\u968F\u624B\u5347
jei_version=29.5.0.24
